  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('DIAS_LABORALES_MES','30', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORAS_LABORALES_DIA','8.5', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORAS_LABORALES_SEMANA','48', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORARIO_NOCTURNO_INICIO','21:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORARIO_NOCTURNO_FIN','06:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORA_INICIAL_ENTRE_SEMANA','07:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORA_FINAL_ENTRE_SEMANA','16:30', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORA_INICIAL_SABADO','07:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORA_FINAL_SABADO','12:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENT)
  VALUES('HORA_INICIAL_DOMINGO','00:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORA_FINAL_DOMINGO','00:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('MINIMO_FESTIVOS_POR_ANO','12', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('MAXIMO_DIAS_PERIODO_PAGO','31', 'HORARRIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORAS_TRABAJAR_MES','240', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RECARGO_NOCTURNO','0.35', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RECARGO_EXTRA_DIURNO','0.25', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RECARGO_EXTRA_NOCTURNO','0.75', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RECARGO_DOMINICAL_FESTIVO','0.75', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('SALARIO_MINIMO_LEGAL_VIGENTE_2020','877803', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('AUXILIO_TRANSPORTE_2020','102854', 'NOMINA');

  --Riesgo Laboral
  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_1','0.00522', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_2','0.01044', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_3','0.02436', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_4','0.0435', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_5','0.0696', 'NOMINA');

  commit;