  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('DIAS_LABORALES_MES','30');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORAS_LABORALES_DIA','8.5');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORAS_LABORALES_SEMANA','48');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORARIO_NOCTURNO_INICIO','21:00');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORARIO_NOCTURNO_FIN','06:00');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORA_INICIAL_ENTRE_SEMANA','07:00');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORA_FINAL_ENTRE_SEMANA','16:30');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORA_INICIAL_SABADO','07:00');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORA_FINAL_SABADO','12:00');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORA_INICIAL_DOMINGO','00:00');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('HORA_FINAL_DOMINGO','00:00');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('MINIMO_FESTIVOS_POR_ANO','12');

  INSERT INTO PARAMETRO(NOMBRE, VALOR)
  VALUES('MAXIMO_DIAS_PERIODO_PAGO','31');

  commit;