  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('DIAS_LABORALES_MES','30', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORAS_LABORALES_DIA','8.5', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORAS_LABORALES_SEMANA','48', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORARIO_NOCTURNO_INICIO','21:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORARIO_NOCTURNO_FIN','06:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORA_INICIAL_ENTRE_SEMANA','07:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORA_FINAL_ENTRE_SEMANA','16:30', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORA_INICIAL_SABADO','07:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORA_FINAL_SABADO','12:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORA_INICIAL_DOMINGO','00:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORA_FINAL_DOMINGO','00:00', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('MINIMO_FESTIVOS_POR_ANO','12', 'HORARIO');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('MAXIMO_DIAS_PERIODO_PAGO','31', 'HORARIO');

  commit;