  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('HORAS_TRABAJAR_MES','240', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RECARGO_NOCTURNO','0.35', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RECARGO_EXTRA_DIURNO','0.25', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RECARGO_EXTRA_NOCTURNO','0.75', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RECARGO_DOMINICAL_FESTIVO','0.75', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('SALARIO_MINIMO_LEGAL_VIGENTE_2020','877803', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('AUXILIO_TRANSPORTE_2020','102854', 'NOMINA');

  commit;