  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('SALUD_EMPLEADO','0.04', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('PENSION_EMPLEADO','0.04', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('SALUD_EMPLEADOR','0.085', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('PENSION_EMPLEADOR','0.12', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('PRIMA','0.0833', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('CESANTIAS','0.0833', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('INTERESES_CESANTIAS','0.12', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('CAJA_COMPENSACION','0.04', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('ICBF','0.03', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('SENA','0.02', 'NOMINA');

  commit;