  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_1','0.00522', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_2','0.01044', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_3','0.02436', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_4','0.0435', 'NOMINA');

  INSERT INTO PARAMETRO(NOMBRE, VALOR, COMPONENTE)
  VALUES('RIESGO_LABORAL_NIVEL_5','0.0696', 'NOMINA');

  commit;